//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asignacion
    {
        public int id_empleado { get; set; }
        public Nullable<int> id_equipo { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual equipo equipo { get; set; }
    }
}
