//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public equipo()
        {
            this.asignacion = new HashSet<asignacion>();
        }
    
        public int id_equipo { get; set; }
        public string no_serie { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public int id_tipo { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<asignacion> asignacion { get; set; }
        public virtual tipo_equipo tipo_equipo { get; set; }
    }
}
