//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permisos
    {
        public permisos()
        {
            this.usuarios = new HashSet<usuarios>();
        }
    
        public int id_permiso { get; set; }
        public string nombre_catalogo { get; set; }
    
        public virtual ICollection<usuarios> usuarios { get; set; }
    }
}
