//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innova_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.permisos = new HashSet<permisos>();
        }
    
        public int id_usuario { get; set; }
        public int id_empleado { get; set; }
        public string contrasena { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual ICollection<permisos> permisos { get; set; }
    }
}
